language: c

compiler: gcc
env: 
  - BOARD=discoveryf4
  - BOARD=discoveryf429
  - BOARD=stm32p103

before_install:
  - sudo apt-get install build-essential
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded

before_script: arm-none-eabi-gcc --version

script:
  - cp -f board/$BOARD/defconfig .config
  - make build/host/Config.in
  - make --no-print-directory -C external/kconfig -f Makefile.f9 conf obj=`pwd`/build/host CC=gcc HOSTCC=gcc
  - build/host/conf --silentoldconfig build/host/Config.in
  - make
  - arm-none-eabi-size build/$BOARD/f9.elf

cache:
  - apt
  - ccache
